/**
 * Central company configuration — every page, the footer, the contact page
 * and the SEO tags read from here. Company facts match our LinkedIn page.
 */
export const SITE = {
  name: 'A&N Software Solutions',
  shortName: 'A&N Software',
  legalName: 'A&N Software Solutions',
  tagline: 'Efficiency powered by innovation',
  url: 'https://www.ansoftwaresolutions.com',
  defaultTitle: 'A&N Software Solutions | IT Recruitment & Technology Services in Hyderabad',
  defaultDescription:
    'A&N Software Solutions helps companies hire skilled, pre-screened professionals for permanent, contract and leadership roles, and delivers software, data, AI and cloud services. Based in Hyderabad.',
  /** Social share images live in /public/og (generated by scripts/generate_brand_assets.py). */
  ogImage: '/og/home.jpg',
  ogImageSize: { width: 1200, height: 630 },

  contact: {
    // Placeholder addresses — replace with your real email once the domain is set up.
    email: 'info@ansoftwaresolutions.com',
    careersEmail: 'jobs@ansoftwaresolutions.com',
    phone: '+91 63007 21736',
    phoneHref: '+916300721736',
    address: {
      city: 'Hyderabad',
      state: 'Telangana',
      zip: '500082',
      country: 'India',
    },
    mapQuery: 'Hyderabad, Telangana 500082',
  },

  social: {
    linkedin: 'https://www.linkedin.com/company/a-nsoftwaresolutions/',
  },
}
